version: '3.8'

services:
  # Ollama - Local LLM inference engine
  ollama:
    image: ollama/ollama:latest
    container_name: boq-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - boq-network
    # Uncomment below if you have NVIDIA GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # Qdrant - Vector database for document embeddings
  qdrant:
    image: qdrant/qdrant:latest
    container_name: boq-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    networks:
      - boq-network

  # Redis - Task queue and caching
  redis:
    image: redis:7-alpine
    container_name: boq-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - boq-network

  # n8n - Workflow automation engine
  n8n:
    image: n8nio/n8n:latest
    container_name: boq-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Toronto
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=smtp.gmail.com
      - N8N_SMTP_PORT=587
      - N8N_SMTP_SSL=false
    volumes:
      - n8n-data:/home/node/.n8n
    restart: unless-stopped
    networks:
      - boq-network

volumes:
  ollama-data:
    driver: local
  qdrant-data:
    driver: local
  redis-data:
    driver: local
  n8n-data:
    driver: local

networks:
  boq-network:
    driver: bridge
