"""final migrations

Revision ID: 0c763c80d042
Revises: 781c002f1605
Create Date: 2025-09-13 01:56:14.198907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c763c80d042'
down_revision: Union[str, Sequence[str], None] = '781c002f1605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_project_access', sa.Column('permission_level', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_project_access', 'permission_level')
    # ### end Alembic commands ###
