"""WBS is not unique

Revision ID: 0cb0694cd662
Revises: bba7e5bf6038
Create Date: 2025-09-17 12:45:23.574145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cb0694cd662'
down_revision: Union[str, Sequence[str], None] = 'bba7e5bf6038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rop_projects_wbs'), table_name='rop_projects')
    op.create_index(op.f('ix_rop_projects_wbs'), 'rop_projects', ['wbs'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rop_projects_wbs'), table_name='rop_projects')
    op.create_index(op.f('ix_rop_projects_wbs'), 'rop_projects', ['wbs'], unique=True)
    # ### end Alembic commands ###
