"""add project foreign key to inventory

Revision ID: 0dfac79ebed1
Revises: d00cadfc5c44
Create Date: 2025-09-14 15:25:15.845083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dfac79ebed1'
down_revision: Union[str, Sequence[str], None] = 'd00cadfc5c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('pid_po', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_inventory_pid_po'), 'inventory', ['pid_po'], unique=False)
    op.create_foreign_key(None, 'inventory', 'projects', ['pid_po'], ['pid_po'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_pid_po'), table_name='inventory')
    op.drop_column('inventory', 'pid_po')
    # ### end Alembic commands ###
