"""added price column to package/lvl1

Revision ID: 0f9b48cbc165
Revises: 2917b73066c6
Create Date: 2025-09-07 14:14:54.195401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f9b48cbc165'
down_revision: Union[str, Sequence[str], None] = '2917b73066c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rop_package_lvl1', sa.Column('price_of_SIs/PCI', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rop_package_lvl1', 'price_of_SIs/PCI')
    # ### end Alembic commands ###
