"""Lead Time Column

Revision ID: 211b17a4cff4
Revises: bf1fa54c11c1
Create Date: 2025-09-09 15:43:50.611860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211b17a4cff4'
down_revision: Union[str, Sequence[str], None] = 'bf1fa54c11c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rop_packages', sa.Column('lead_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rop_packages', 'lead_time')
    # ### end Alembic commands ###
