"""Radio FTK-Radio

Revision ID: 21aade482495
Revises: 68111619e581
Create Date: 2025-10-06 11:01:31.360931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21aade482495'
down_revision: Union[str, Sequence[str], None] = '68111619e581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ranlvl3', sa.Column('ran_category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ranlvl3', 'ran_category')
    # ### end Alembic commands ###
