"""added price column to package

Revision ID: 2917b73066c6
Revises: 9d9ed04a06f5
Create Date: 2025-09-07 11:34:07.760085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2917b73066c6'
down_revision: Union[str, Sequence[str], None] = '9d9ed04a06f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rop_packages', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rop_packages', 'price')
    # ### end Alembic commands ###
