"""Turning Key into String

Revision ID: 447f28a00543
Revises: 055df8ca1deb
Create Date: 2025-09-10 13:04:20.945934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '447f28a00543'
down_revision: Union[str, Sequence[str], None] = '055df8ca1deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_project_access')
    op.alter_column('ran_lld', 'key',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('ranlvl3', 'key',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ranlvl3', 'key',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('ran_lld', 'key',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_table('user_project_access',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('permission_level', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.pid_po'], name=op.f('FK__user_proj__proje__2610A626'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('FK__user_proj__user___251C81ED'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__user_pro__3213E83F3CDA0AB0'))
    )
    # ### end Alembic commands ###