"""UPL Line

Revision ID: 5fe553198beb
Revises: 66e1d1aeee53
Create Date: 2025-10-08 11:13:12.111602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe553198beb'
down_revision: Union[str, Sequence[str], None] = '66e1d1aeee53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lvl3', sa.Column('upl_line', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lvl3', 'upl_line')
    # ### end Alembic commands ###
