"""add poline/caregory to Ran Level3

Revision ID: 64257a4028ea
Revises: 69d34b85fd01
Create Date: 2025-09-16 11:24:21.700394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64257a4028ea'
down_revision: Union[str, Sequence[str], None] = '69d34b85fd01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ranlvl3', sa.Column('po_line', sa.String(length=100), nullable=True))
    op.add_column('ranlvl3', sa.Column('category', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ranlvl3', 'category')
    op.drop_column('ranlvl3', 'po_line')
    # ### end Alembic commands ###
