"""Antenna Serials

Revision ID: 66e1d1aeee53
Revises: c10d9ee966ca
Create Date: 2025-10-06 14:33:12.973193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e1d1aeee53'
down_revision: Union[str, Sequence[str], None] = 'c10d9ee966ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ran_antenna_serials_id'), table_name='ran_antenna_serials')
    op.drop_index(op.f('ix_ran_antenna_serials_project_id'), table_name='ran_antenna_serials')
    op.drop_table('ran_antenna_serials')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ran_antenna_serials',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('mrbts', sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('antenna_model', sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('serial_number', sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['ran_projects.pid_po'], name=op.f('FK__ran_anten__proje__7D98A078')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__ran_ante__3213E83F5A7E4DD8'))
    )
    op.create_index(op.f('ix_ran_antenna_serials_project_id'), 'ran_antenna_serials', ['project_id'], unique=False)
    op.create_index(op.f('ix_ran_antenna_serials_id'), 'ran_antenna_serials', ['id'], unique=False)
    # ### end Alembic commands ###
