"""UPL Line

Revision ID: 68111619e581
Revises: ad21132bf4b5
Create Date: 2025-09-28 16:52:08.146290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68111619e581'
down_revision: Union[str, Sequence[str], None] = 'ad21132bf4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items_for_ranlvl3', sa.Column('upl_line', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items_for_ranlvl3', 'upl_line')
    # ### end Alembic commands ###
