"""add pidpo to both Dismantling

Revision ID: 69d34b85fd01
Revises: 92ed23097d60
Create Date: 2025-09-15 22:25:36.482830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69d34b85fd01'
down_revision: Union[str, Sequence[str], None] = '92ed23097d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dismantling', sa.Column('pid_po', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_dismantling_pid_po'), 'dismantling', ['pid_po'], unique=False)
    op.create_foreign_key(None, 'dismantling', 'projects', ['pid_po'], ['pid_po'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dismantling', type_='foreignkey')
    op.drop_index(op.f('ix_dismantling_pid_po'), table_name='dismantling')
    op.drop_column('dismantling', 'pid_po')
    # ### end Alembic commands ###
