"""Total_Quantity_in_PackageLvl1Table

Revision ID: 6c0a4e75686a
Revises: c960eb986f45
Create Date: 2025-09-24 13:13:19.072006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0a4e75686a'
down_revision: Union[str, Sequence[str], None] = 'c960eb986f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rop_package_lvl1', sa.Column('total_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rop_package_lvl1', 'total_quantity')
    # ### end Alembic commands ###
