"""create ran projects

Revision ID: 7eea7e66e70c
Revises: 64257a4028ea
Create Date: 2025-09-16 14:34:19.412476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eea7e66e70c'
down_revision: Union[str, Sequence[str], None] = '64257a4028ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_project_access', sa.Column('Ranproject_id', sa.String(length=200), nullable=False))
    op.create_foreign_key(None, 'user_project_access', 'ran_projects', ['Ranproject_id'], ['pid_po'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_project_access', type_='foreignkey')
    op.drop_column('user_project_access', 'Ranproject_id')
    # ### end Alembic commands ###
