"""add pidpo to both lld/boqRef

Revision ID: 92ed23097d60
Revises: 0dfac79ebed1
Create Date: 2025-09-15 22:15:28.475345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ed23097d60'
down_revision: Union[str, Sequence[str], None] = '0dfac79ebed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boq_reference', sa.Column('pid_po', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'boq_reference', 'projects', ['pid_po'], ['pid_po'])
    op.add_column('lld', sa.Column('pid_po', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_lld_pid_po'), 'lld', ['pid_po'], unique=False)
    op.create_foreign_key(None, 'lld', 'projects', ['pid_po'], ['pid_po'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lld', type_='foreignkey')
    op.drop_index(op.f('ix_lld_pid_po'), table_name='lld')
    op.drop_column('lld', 'pid_po')
    op.drop_constraint(None, 'boq_reference', type_='foreignkey')
    op.drop_column('boq_reference', 'pid_po')
    # ### end Alembic commands ###
