"""creating projects ids

Revision ID: 950ca58520c4
Revises: 7eea7e66e70c
Create Date: 2025-09-16 14:41:53.389610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '950ca58520c4'
down_revision: Union[str, Sequence[str], None] = '7eea7e66e70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ran_inventory', sa.Column('pid_po', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_ran_inventory_pid_po'), 'ran_inventory', ['pid_po'], unique=False)
    op.create_foreign_key(None, 'ran_inventory', 'ran_projects', ['pid_po'], ['pid_po'])
    op.add_column('ran_lld', sa.Column('pid_po', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_ran_lld_pid_po'), 'ran_lld', ['pid_po'], unique=False)
    op.create_foreign_key(None, 'ran_lld', 'ran_projects', ['pid_po'], ['pid_po'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ran_lld', type_='foreignkey')
    op.drop_index(op.f('ix_ran_lld_pid_po'), table_name='ran_lld')
    op.drop_column('ran_lld', 'pid_po')
    op.drop_constraint(None, 'ran_inventory', type_='foreignkey')
    op.drop_index(op.f('ix_ran_inventory_pid_po'), table_name='ran_inventory')
    op.drop_column('ran_inventory', 'pid_po')
    # ### end Alembic commands ###
