"""Change column types

Revision ID: 9d9ed04a06f5
Revises: 
Create Date: 2025-09-06 18:38:04.643551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d9ed04a06f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items_for_lvl3', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('lvl1', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('lvl3', 'total_price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('ix_sites_site_id'), table_name='sites')
    op.create_index(op.f('ix_sites_site_id'), 'sites', ['site_id'], unique=False)
    op.drop_index(op.f('ix_sites_site_name'), table_name='sites')
    op.create_index(op.f('ix_sites_site_name'), 'sites', ['site_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sites_site_name'), table_name='sites')
    op.create_index(op.f('ix_sites_site_name'), 'sites', ['site_name'], unique=True)
    op.drop_index(op.f('ix_sites_site_id'), table_name='sites')
    op.create_index(op.f('ix_sites_site_id'), 'sites', ['site_id'], unique=True)
    op.alter_column('lvl3', 'total_price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('lvl1', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('items_for_lvl3', 'price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
