"""UPL Line

Revision ID: ad21132bf4b5
Revises: d1c3ef090337
Create Date: 2025-09-28 16:47:14.016026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad21132bf4b5'
down_revision: Union[str, Sequence[str], None] = 'd1c3ef090337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ranlvl3', sa.Column('upl_line', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ranlvl3', 'upl_line')
    # ### end Alembic commands ###
