"""add created by

Revision ID: b0ed32c39cfb
Revises: 0cb0694cd662
Create Date: 2025-09-17 23:06:08.629643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ed32c39cfb'
down_revision: Union[str, Sequence[str], None] = '0cb0694cd662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rop_projects', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rop_projects_created_by'), 'rop_projects', ['created_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rop_projects_created_by'), table_name='rop_projects')
    op.drop_column('rop_projects', 'created_by')
    # ### end Alembic commands ###
