"""ropPidpo added

Revision ID: bba7e5bf6038
Revises: 3980e913eac1
Create Date: 2025-09-17 11:19:23.987954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba7e5bf6038'
down_revision: Union[str, Sequence[str], None] = '3980e913eac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_project_access', sa.Column('Ropproject_id', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'user_project_access', 'rop_projects', ['Ropproject_id'], ['pid_po'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_project_access', type_='foreignkey')
    op.drop_column('user_project_access', 'Ropproject_id')
    # ### end Alembic commands ###
