"""remove price column to package/lvl1

Revision ID: bf1fa54c11c1
Revises: 0f9b48cbc165
Create Date: 2025-09-07 15:18:15.913759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf1fa54c11c1'
down_revision: Union[str, Sequence[str], None] = '0f9b48cbc165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rop_package_lvl1', 'price_of_SIs/PCI')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rop_package_lvl1', sa.Column('price_of_SIs/PCI', sa.FLOAT(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
