"""Package Currency

Revision ID: c960eb986f45
Revises: 7fad86d319c9
Create Date: 2025-09-23 18:10:31.009205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c960eb986f45'
down_revision: Union[str, Sequence[str], None] = '7fad86d319c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rop_packages', sa.Column('currency', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rop_packages', 'currency')
    # ### end Alembic commands ###
