"""Consumption in RopLvl1

Revision ID: d1c3ef090337
Revises: 6c0a4e75686a
Create Date: 2025-09-24 13:33:27.698123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c3ef090337'
down_revision: Union[str, Sequence[str], None] = '6c0a4e75686a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rop_lvl1', sa.Column('consumption', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rop_lvl1', 'consumption')
    # ### end Alembic commands ###
