"""UPL Line for lvl3 items

Revision ID: f8c4ee8e0262
Revises: 5fe553198beb
Create Date: 2025-10-08 11:17:47.836931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c4ee8e0262'
down_revision: Union[str, Sequence[str], None] = '5fe553198beb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items_for_lvl3', sa.Column('upl_line', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items_for_lvl3', 'upl_line')
    # ### end Alembic commands ###
